# Dockerfile.streamlit
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY streamlitApp.py .

CMD ["streamlit", "run", "streamlitApp.py", "--server.port=8501", "--server.address=0.0.0.0"]
